/**
 * Visible P2P (Peer to Peer) copy for the People tab.
 * Interaction logic should import from here only so wording can change
 * without touching join/leave/nav. Internal code stays pair_up.
 */
export const peopleUiCopy = {
  rowAction: "P2P",
  joinToastTitle: "Down to go with someone ✌️",
  /** Narrow viewport (e.g. 320) — keep one-row capsule. */
  joinToastTitleCompact: "Down to go ✌️",
  joinToastTitleLead: "Down to go",
  joinToastTitleRest: "with someone",
  joinToastTitleEmoji: "✌️",
  /** Kept for a later two-line toast; Toaster is currently single-line. */
  joinToastSupporting: "See who you sync with.",
  joinToastAddNote: "Add note",
  joinToastUndo: "Undo",
  /** Icon-only remove on Duo success toast. */
  joinToastUndoAria: "Undo Duo",
  manageTitle: "Duo",
  manageAddNote: "Add note",
  manageEditNote: "Edit note",
  manageLeave: "Leave Duo",
  noteSheetTitleAdd: "Add a note",
  noteSheetTitleEdit: "Edit note",
  noteSheetHelper: "Anything people should know?",
  noteSheetPlaceholder:
    "Say what kind of person you’d vibe with… #What’s your energy?",
  noteSheetPlaceholderLine1: "Say what kind of person you’d vibe with…",
  noteSheetPlaceholderLine2: "#What’s your energy?",
  noteSheetSave: "Save",
  noteSheetCancel: "Cancel",
  noteSheetClear: "Clear",
  noteSaveError: "Couldn't save note.",
  leaveTitle: "Leave Duo?",
  leaveBody: "You'll stop showing as down for this.",
  leaveConfirm: "Leave",
  leaveCancel: "Stay",
  leaveError: "Couldn't leave.",
  joinError: "Couldn't join.",
  undoError: "Couldn't undo.",
  /** Place Duo / Open Plan — visible product language stays Duo */
  openPlanCreateTitle: "Duo",
  openPlanCreateCta: "Save",
  openPlanCreateSuccess: "Your Open Plan is ready ✌️",
  /** Create-success toast title parts (showOpenPlanJoinToast). */
  openPlanCreateSuccessLead: "Your Open Plan is ready",
  openPlanCreateSuccessRest: "",
  openPlanCreateSuccessEmoji: "✌️",
  openPlanCreateError: "Couldn't go down for this.",
  openPlanDateLabel: "Date",
  openPlanTimeLabel: "Time",
  openPlanChooseDate: "Choose a date",
  openPlanDateTime: "Date & time",
  openPlanAddTime: "Add time",
  openPlanClearTime: "Clear time",
  planScheduleOptional: "(optional)",
  planScheduleAddDateTime: "Add date & time",
  openPlanNoteLabel: "Note",
  openPlanNoteOptional: "(optional)",
  openPlanNotePlaceholder: "Optional note",
  openPlanPastError: "Pick a future date.",
  openPlanManageTitle: "Duo",
  openPlanDiscardTitle: "You’re exiting Duo",
  openPlanDiscardBody: "Commit before you go?",
  openPlanDiscardKeep: "Keep editing",
  openPlanDiscardExit: "Exit",
  openPlanCancelCta: "Leave Duo",
  openPlanCancelTitle: "Leave Duo?",
  openPlanCancelBody:
    "You'll stop offering this. Pending requests will be closed.",
  openPlanCancelConfirm: "Leave",
  openPlanCancelKeep: "Stay",
  openPlanCancelError: "Couldn't leave.",
  openPlanCancelSuccess: "Left Duo",
  openPlanScheduledLabel: "When",
  /** Aligned with create-success toast; create UI reads openPlanCreateSuccess*. */
  openPlanJoinToastLead: "Your Open Plan is ready",
  openPlanJoinToastRest: "",
  openPlanJoinToastEmoji: "✌️",
  openPlanJoinToastUndoAria: "Undo Place Duo",
  launcherLabel: "P2P",
  launcherSupporting: "Peer to Peer",
  matchDeck: "People",
  emptyList: "No P2P plans yet.",
  /** User-facing Duo destination (internal scope remains my_plans). */
  scopeMyPlans: "Duo",
  scopeDiscover: "Discover",
  scopeOpenPlans: "Plans",
  openPlansEmpty: "No open plans right now.",
  openPlansImDown: "I'm down",
  openPlansRequested: "Requested",
  openPlansWithdraw: "Withdraw",
  openPlansRequestError: "Couldn't send request.",
  openPlansWithdrawError: "Couldn't withdraw.",
  openPlansAlreadyAccepted:
    "Already accepted — check Messages.",
  openPlansPrivacyLine:
    "Requesting shares your name and photo with the host.",
  openPlansNoteLabel: "Note",
  openPlansNoteExpand: "Expand plan note",
  openPlansNoteCollapse: "Collapse plan note",
  openPlansNoteEmpty: "No plan note",
  /** Creator Messages → Requests (incoming Open Plan) */
  openPlanIncomingAccept: "Accept",
  /** Legacy flat host row (unused by grouped inbox). */
  openPlanIncomingPrivacyLine: "Name is revealed after acceptance.",
  openPlanRequesterNameHidden: "Name hidden",
  openPlanIncomingUnavailable: "This plan is no longer available.",
  openPlanIncomingAcceptError: "Couldn't accept request.",
  openPlanIncomingAcceptMissingDm:
    "Couldn't open the conversation. Try again.",
  openPlanIncomingLabel: "Open Plan",
  openPlanRequestGroupOpen: "View requests",
  openPlanRequestGroupYours: "Plan",
  openPlanRequestGroupViewPost: "View post",
  openPlanRequestersEmpty: "No pending requests.",
  openPlanRequestersLoadError: "Couldn't load requests.",
  discoverIntroTitle: "Meet people outside your plans",
  discoverIntroBody:
    "Discover lets you meet people outside your shared plans. When People discoverability is on, your eligible Duos for public events can also appear to others in Discover, and your active Duos and hosted Groups may show on your Profile.",
  discoverIntroContinue: "Continue",
  discoverIntroNotNow: "Not now",
  discoverEmpty: "No new people to discover right now.",
  discoverAddedToP2p: "Added to P2P",
  discoverToggleError: "Couldn't update People discoverability.",
  discoverToggleOnSuccess: "Discover turned on",
  discoverToggleOffSuccess: "Discover turned off",
  discoverToggleTurnOff: "Turn off",
  /** Profile Privacy settings */
  profileDiscoverTitle: "People discoverability",
  profileDiscoverBody:
    "When on, you can browse Discover, eligible Duos may appear there, and your active Duos and hosted Groups may show on your Profile. When off, those Profile opportunities stay hidden and Discover is locked — joining a specific Event Duo you choose still works.",
  groupUp: "Group Up",
  groupUpCreateTitle: "Group",
  groupUpCreateCta: "Create group",
  groupUpCreateSuccess: "Group Up created",
  groupUpCreateError: "Couldn't create group. Try again.",
  groupUpSourceLabel: "Source",
  groupUpNameLabel: "Group name",
  groupUpNamePlaceholder: "Group name",
  groupUpDescriptionLabel: "Description",
  groupUpDescriptionPlaceholder: "Write your group description here",
  groupUpDiscardTitle: "You’re exiting Group",
  groupUpDiscardBody: "Save it before you go?",
  groupUpDiscardKeep: "Keep editing",
  groupUpDiscardExit: "Exit",
  groupUpManageTitle: "Group",
  groupUpDiscoverableLabel: "Discoverable until",
  groupUpOpenGroup: "Open group",
  groupUpCancelCta: "Cancel group",
  groupUpCancelTitle: "Cancel group?",
  groupUpCancelBody:
    "New people won’t be able to request. Your group chat will stay open.",
  groupUpCancelConfirm: "Cancel group",
  groupUpCancelKeep: "Keep group",
  groupUpCancelError: "Couldn't cancel group.",
  groupUpCancelSuccess: "Group canceled",
  groupUpRenewCta: "Renew Group Up",
  groupUpRenewTitle: "Renew Group Up",
  groupUpRenewSuccess: "Group Up renewed",
  groupUpRenewError: "Couldn't renew Group Up.",
  groupUpScheduleLabel: "When",
  groupUpNoDateSet: "No date set",
  groupUpScheduleSave: "Save schedule",
  groupUpScheduleRemove: "Remove date",
  groupUpScheduleUpdateSuccess: "Schedule updated",
  groupUpScheduleUpdateError: "Couldn't update schedule.",
  groupUpScheduleDone: "Done",
  groupUpClose: "Close",
  groupUpFallbackTitle: "Group",
  groupUpPastError: "Pick a future date and time.",
  groupUpSourceSectionLabel: "Source",
  groupUpBrowseEmpty: "No active groups right now.",
  groupUpBrowseTabNew: "New",
  groupUpBrowseTabYours: "Yours",
  groupUpBrowseNewEmpty: "No new groups right now.",
  groupUpBrowseYoursEmpty: "Your requests and groups will show here.",
  groupUpBrowseHostLabel: "Host",
  groupUpBrowseMemberLabel: "Member",
  groupUpRequestSentToast: "Request sent",
  groupUpBrowseJoin: "Join",
  groupUpBrowseRequested: "Requested",
  groupUpBrowseWithdraw: "Withdraw",
  groupUpBrowseYourGroup: "Your group",
  groupUpBrowseRequestError: "Couldn't send request.",
  groupUpBrowseWithdrawError: "Couldn't withdraw.",
  groupUpBrowseFull: "This group is full.",
  groupUpBrowseUnavailable: "This group is no longer available.",
  groupUpBrowseDeclined: "You can't request this group again.",
  groupUpBrowseBlocked: "Can't request this group.",
  groupUpBrowseAlreadyMember: "You're already in this group.",
  groupUpBrowseHostedBy: "Hosted by",
  groupUpBrowseTypeEvent: "Event",
  groupUpBrowseTypePlace: "Post",
  groupUpIncomingLabel: "Group Up",
  groupUpIncomingSomeone: "Someone",
  groupUpIncomingAccept: "Accept",
  groupUpIncomingDecline: "Decline",
  groupUpIncomingAcceptError: "Couldn't accept this request.",
  groupUpIncomingDeclineError: "Couldn't decline this request.",
  groupUpIncomingUnavailable: "This Group Up is no longer available.",
  groupUpIncomingAcceptSuccess: "Accepted — they're in the group.",
  groupUpIncomingDeclineSuccess: "Request declined.",
  groupUpRequestGroupLabel: "Group Up",
  groupUpRequestGroupViewPost: "View post",
  groupUpRequestGroupOpen: "View requests",
  groupUpRequestersTitle: "Requests",
  groupUpRequestersEmpty: "No pending requests.",
  groupUpRequestersLoadError: "Couldn't load requests.",
  groupUpCreateNameRequired: "Group name is required.",
  groupUpCreateDescriptionRequired: "Description is required.",
  p2pNoteLabel: "P2P",
  /** Empty Duo note spacer — no invented intent. */
  duoNoteEmpty: "No note added",
  duoNoteExpand: "Expand opportunity note",
  duoNoteCollapse: "Collapse opportunity note",
  duoNoteClose: "Close opportunity note",
  /** Small decorative label under the person name in the floating note panel. */
  duoNoteSectionLabel: "Note",
  /** Groups floating note header section. */
  groupUpNoteSectionLabel: "About",
  groupUpNoteEmpty: "No description",
  duoNoteExpandAffordance: "More",
  duoNoteCollapseAffordance: "Less",
  deckRetryComplete: "Retry",
  deckRetryLoad: "Try again",
  deckLoadError: "Couldn't load people.",
  deckCaughtUp: "You're all caught up.",
  deckNoActive: "Join a P2P plan to start matching.",
  deckEmpty: "No people to match right now.",
  deckCompleteError: "Couldn't open the conversation.",
  deckExpressError: "Couldn't connect right now. Try again.",
  deckConnectUnavailable: "This plan is no longer available.",
  deckGroupsEmpty: "No groups to browse yet.",
  deckCheckGroups: "Check Groups",
  deckCheckPeople: "Back to People",
  deckSeePost: "See post",
  deckClose: "Close Match Deck",
  deckConnect: "Send P2P",
  deckPrev: "Previous person",
  deckNext: "Next person",
  deckOpenProfile: "Open profile",
  deckCloseLabel: "Close",
  deckConnectLabel: "Connect",
  deckConnectedLabel: "Connected",
  /** Profile rail Connect success (same Duo toast layout). */
  profileConnectToast: "You're connected",
  profileConnectToastUndoAria: "Undo connect",
  profileDisconnectedToast: "You're no longer connected",
  profileDisconnectedToastUndoAria: "Undo leave",
  deckPrevLabel: "Prev",
  deckNextLabel: "Next",
  /** People shell Phase 1A dock / strip */
  shellDockAria: "People navigation",
  shellSubmodeAria: "People submodes",
  shellModeSwitchAria: "People destinations",
  shellBack: "Back",
  shellDuo: "Duo",
  shellGroups: "Groups",
  /** Groups Back-adjacent Yours toggle (discovery → Yours). */
  groupUpYoursControlAria: "Your groups",
  /** Visible label on Groups discovery secondary control. */
  groupUpYoursControlLabel: "Yours",
  /** Groups Back-adjacent Yours toggle (Yours → discovery). */
  groupUpDiscoverControlAria: "Discover groups",
  /** Visible label on Groups Yours secondary control. */
  groupUpDiscoverControlLabel: "Discover",
  /** Subtle context label above Groups action while browsing Yours. */
  groupUpYoursContextLabel: "Your groups",
  /** Shell-facing Group idle CTA (none → request_group_up). Copy only; RPC unchanged. */
  groupUpShellRequest: "Join",
  groupUpShellOpen: "Open",
} as const;
